from pathlib import Path
p=Path('bomber3d/rig-lab.html')
s=p.read_text(encoding='utf-8')
if 'RIG LAB v3.1' in s:
    print('Rig Lab v3.1 already applied'); raise SystemExit(0)
s=s.replace('<b>RIG LAB v3.0</b>','<b>RIG LAB v3.1</b>')
s=s.replace("<span class=\"pill\">arrastrá fondo para girar</span>","<span class=\"pill\">arrastrá fondo para girar</span><span class=\"pill\">reordená KayKit sólo desde ⋮⋮</span>")
s=s.replace('.axisRow.dragging{opacity:.45}', '.axisRow.dragging{opacity:.45}.dragHandle{cursor:grab;touch-action:none;user-select:none;padding:3px 5px;border-radius:6px;border:1px solid var(--line);color:var(--muted);font-weight:900}.moveGrid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.moveBox{border:1px solid var(--line);border-radius:11px;padding:9px;background:#10151a}.moveRow{display:grid;grid-template-columns:22px 1fr 48px;gap:6px;align-items:center;margin:6px 0}')
s=s.replace("<div class=\"hint\">Los dos lados son independientes. Mové X/Y/Z de un modelo y mirá el giro. En KayKit podés <b>reordenar las tres filas</b> con ↑/↓ o arrastrándolas para poner cada eje enfrente de su correspondiente Hunyuan. Cuando quieras probarlos juntos, activá <b>VINCULAR FILAS</b>.</div>","<div class=\"hint\">Los dos lados son independientes. Mové X/Y/Z de un modelo y mirá el giro. En KayKit podés <b>reordenar las filas</b> con ↑/↓ o agarrando exclusivamente el control <b>⋮⋮</b>. Los sliders nunca disparan drag-and-drop. Cuando quieras probarlos juntos, activá <b>VINCULAR FILAS</b>.</div>")
s=s.replace('<div class="axisRow" draggable="true" data-axis="x"><span class="axisLetter axisX">X</span>','<div class="axisRow" data-axis="x"><span class="dragHandle" draggable="true" title="Arrastrar fila">⋮⋮</span><span class="axisLetter axisX">X</span>')
s=s.replace('<div class="axisRow" draggable="true" data-axis="y"><span class="axisLetter axisY">Y</span>','<div class="axisRow" data-axis="y"><span class="dragHandle" draggable="true" title="Arrastrar fila">⋮⋮</span><span class="axisLetter axisY">Y</span>')
s=s.replace('<div class="axisRow" draggable="true" data-axis="z"><span class="axisLetter axisZ">Z</span>','<div class="axisRow" data-axis="z"><span class="dragHandle" draggable="true" title="Arrastrar fila">⋮⋮</span><span class="axisLetter axisZ">Z</span>')
s=s.replace('.axisRow{display:grid;grid-template-columns:30px 1fr 50px;', '.axisRow{display:grid;grid-template-columns:30px 1fr 50px;')
s=s.replace('#view{height:45vh;min-height:285px}.axisLab', '#view{height:45vh;min-height:285px}.moveGrid{grid-template-columns:1fr}.axisLab')
insert='''\n<section class="card">\n<div class="title">3 · Mover modelos completos (sólo encuadre)</div>\n<div class="small">Esto NO forma parte de la calibración. Sirve sólo para volver a centrar/separar los modelos.</div>\n<div class="moveGrid">\n<div class="moveBox"><b>Hunyuan</b>\n<div class="moveRow"><span class="axisX">X</span><input id="hpx" type="range" min="-3" max="3" step="0.05" value="-1.35"><span id="hpxv" class="value">-1.35</span></div>\n<div class="moveRow"><span class="axisY">Y</span><input id="hpy" type="range" min="-2" max="3" step="0.05" value="0"><span id="hpyv" class="value">0.00</span></div>\n<div class="moveRow"><span class="axisZ">Z</span><input id="hpz" type="range" min="-3" max="3" step="0.05" value="0"><span id="hpzv" class="value">0.00</span></div><button id="centerH">Centrar Hunyuan</button></div>\n<div class="moveBox"><b>KayKit</b>\n<div class="moveRow"><span class="axisX">X</span><input id="kpx" type="range" min="-3" max="3" step="0.05" value="1.35"><span id="kpxv" class="value">1.35</span></div>\n<div class="moveRow"><span class="axisY">Y</span><input id="kpy" type="range" min="-2" max="3" step="0.05" value="0"><span id="kpyv" class="value">0.00</span></div>\n<div class="moveRow"><span class="axisZ">Z</span><input id="kpz" type="range" min="-3" max="3" step="0.05" value="0"><span id="kpzv" class="value">0.00</span></div><button id="centerK">Centrar KayKit</button></div>\n</div>\n<div class="row" style="margin-top:8px"><button id="centerBoth">Restaurar encuadre inicial</button></div>\n</section>\n'''
s=s.replace('<section class="card">\n<div class="title">3 · Resultado acumulado</div>',insert+'<section class="card">\n<div class="title">4 · Resultado acumulado</div>')
s=s.replace("let scene,camera,renderer,hRoot,kRoot,hSkin", "let scene,camera,renderer,hRoot,kRoot,hBasePos=new THREE.Vector3(),kBasePos=new THREE.Vector3(),hSkin")
s=s.replace("hRoot.position.x-=1.35;kRoot.position.x+=1.35;scene.add(hRoot,kRoot);", "hRoot.position.x-=1.35;kRoot.position.x+=1.35;hBasePos.copy(hRoot.position);kBasePos.copy(kRoot.position);scene.add(hRoot,kRoot);")
js='''\nfunction applyModelPos(side){const root=side==='h'?hRoot:kRoot,base=side==='h'?hBasePos:kBasePos;if(!root)return;const pre=side==='h'?'h':'k';root.position.set(base.x+(+$(`${pre}px`).value-(side==='h'?-1.35:1.35)),base.y+(+$(`${pre}py`).value),base.z+(+$(`${pre}pz`).value));for(const a of ['x','y','z'])$(`${pre}p${a}v`).textContent=(+$(`${pre}p${a}`).value).toFixed(2);root.updateMatrixWorld(true)}\nfunction resetModelPos(side){const pre=side==='h'?'h':'k';$(`${pre}px`).value=side==='h'?-1.35:1.35;$(`${pre}py`).value=0;$(`${pre}pz`).value=0;applyModelPos(side)}\nfor(const side of ['h','k'])for(const a of ['x','y','z'])$(`${side}p${a}`).addEventListener('input',()=>applyModelPos(side));\n$('centerH').addEventListener('click',()=>resetModelPos('h'));$('centerK').addEventListener('click',()=>resetModelPos('k'));$('centerBoth').addEventListener('click',()=>{resetModelPos('h');resetModelPos('k')});\n'''
s=s.replace("canvas.addEventListener('pointerdown'",js+"\ncanvas.addEventListener('pointerdown'")
s=s.replace("$('kRows').addEventListener('dragstart',e=>{dragRow=e.target.closest('.axisRow');if(dragRow)dragRow.classList.add('dragging')});", "$('kRows').addEventListener('dragstart',e=>{if(!e.target.classList.contains('dragHandle')){e.preventDefault();return}dragRow=e.target.closest('.axisRow');if(dragRow)dragRow.classList.add('dragging')});")
s=s.replace("window.__rigLabReady={hBones:hBones.length,kBones:kBones.length,version:'3.0'}", "window.__rigLabReady={hBones:hBones.length,kBones:kBones.length,version:'3.1'}")
p.write_text(s,encoding='utf-8')
print('Applied Rig Lab v3.1')
